#!/bin/zsh
#disp
#dmenu script to select display settings

DPNAME=$(xrandr | grep -v disconnected | grep DP | grep -v eDP)
eDPNAME=$(xrandr | grep -v disconnected | grep eDP)
HDMINAME=$(xrandr | grep -v disconnected | grep HDMI)
DPNAME=${DPNAME%% *}
eDPNAME=${eDPNAME%% *}
HDMINAME=${HDMINAME%% *}

if [[ -n $DPNAME && -n $HDMINAME ]]; then
    choices="triple\n${HDMINAME}\n${DPNAME}\n${HDMINAME}proj\n${DPNAME}proj\neDP1080";
else
    if [[ -n $HDMINAME ]]; then; choices="${HDMINAME}\n${HDMINAME}proj\neDP1080"; fi;
    if [[ -n $DPNAME ]]; then; choices="${DPNAME}\n${DPNAME}proj\neDP1080"; fi;
fi

chosen=$(echo -e "$choices" | dmenu -m "0" -fn "noto:size=10" -nb "#222222" -nf "#bbbbbb" -sb "#005577" -sf "#eeeeee" -i)

case "$chosen" in
    triple) if [[ -n $DPNAME && -n $HDMINAME ]]; then; xrandr --output $eDPNAME --mode 1920x1080 --output $HDMINAME --auto --right-of $eDPNAME --output $DPNAME --auto --right-of $HDMINAME; fi ;;
    $HDMINAME) if [[ -n $HDMINAME ]]; then; xrandr --output $eDPNAME --mode 1920x1080 --output $HDMINAME --mode 1920x1080 --right-of $eDPNAME; fi ;;
    ${HDMINAME}proj) if [[ -n $HDMINAME ]]; then; xrandr --output $eDPNAME --mode 1920x1080 --output $HDMINAME --auto --same-as $eDPNAME; fi ;;
    $DPNAME) if [[ -n $DPNAME ]]; then; xrandr --output $eDPNAME --mode 1920x1080 --output $DPNAME --auto --right-of $eDPNAME; fi ;;
    ${DPNAME}proj) if [[ -n $DPNAME ]]; then; xrandr --output $DPNAME --auto --same-as $eDPNAME; fi ;;
    eDP1080) xrandr --output $eDPNAME --auto ;;
esac
~/.fehbg
