#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if $(setxkbmap -query | grep layout | grep -q ie); then
  notify-send "Keyboard" "ru"
  setxkbmap -layout ru
else
  notify-send "Keyboard" "ie"
  setxkbmap -layout ie
fi
